[package]
name = "yogcrypt"
version = "0.1.0"
authors = ["The yogcrypt Project Contributors"]
readme = "README.md"
license = "MIT/Apache-2.0"
description = """
A high-performance, general purpose crypto library
"""

[dependencies]
rand = "0.5.4"
lazy_static = "1.0.2"
